In [26]:
import seaborn as sb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
data = pd.read_csv('../data/trip_duration_task.csv')

In [4]:
data

id  vendor_id      pickup_datetime     dropoff_datetime  \
0       id1080784        2.0  2016-02-29 16:40:21  2016-02-29 16:47:01   
1       id0889885        1.0  2016-03-11 23:35:37  2016-03-11 23:53:57   
2       id0857912        2.0  2016-02-21 17:59:33  2016-02-21 18:26:48   
3       id3744273        2.0  2016-01-05 09:44:31  2016-01-05 10:03:32   
4       id0232939        1.0  2016-02-17 06:42:23  2016-02-17 06:56:31   
...           ...        ...                  ...                  ...   
729317  id3905982        2.0  2016-05-21 13:29:38  2016-05-21 13:34:34   
729318  id0102861        1.0  2016-02-22 00:43:11  2016-02-22 00:48:26   
729319  id0439699        1.0  2016-04-15 18:56:48  2016-04-15 19:08:01   
729320  id2078912        1.0  2016-06-19 09:50:47  2016-06-19 09:58:14   
729321  id1053441        2.0  2016-01-01 17:24:16  2016-01-01 17:44:40   

        passenger_count  pickup_longitude  pickup_latitude  dropoff_longitude  \
0                     1        -73.953918        40.778873         -73.963875   
1                     2        -73.988312        40.731743         -73.994751   
2                     2        -73.997314        40.721458         -73.948029   
3                     6        -73.961670        40.759720         -73.956779   
4                     1        -74.017120        40.708469         -73.988182   
...                 ...               ...              ...                ...   
729317                2        -73.965919        40.789780         -73.952637   
729318                1        -73.996666        40.737434         -74.001320   
729319                1        -73.997849        40.761696         -74.001488   
729320                1        -74.006706        40.708244         -74.013550   
729321                4        -74.003342        40.743839         -73.945847   

        dropoff_latitude  trip_duration  
0              40.771164            400  
1              40.694931           1100  
2              40.774918           1635  
3              40.780628           1141  
4              40.740631            848  
...                  ...            ...  
729317         40.789181            296  
729318         40.731911            315  
729319         40.741207            673  
729320         40.713814            447  
729321         40.712841           1224  

[729322 rows x 10 columns]

In [89]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
  
# Ridge Regression
  
class RidgeRegression() :
      
    def __init__( self, learning_rate, iterations, l2_penality ) :
          
        self.learning_rate = learning_rate        
        self.iterations = iterations        
        self.l2_penality = l2_penality
          
    # Function for model training            
    def fit( self, X, Y ) :
          
        # no_of_training_examples, no_of_features        
        self.m, self.n = X.shape
          
        # weight initialization        
        self.W = np.zeros( self.n )
          
        self.b = 0        
        self.X = X        
        self.Y = Y
          
        # gradient descent learning
                  
        for i in range( self.iterations ) :            
            self.update_weights()      
        return self
      
    # Helper function to update weights in gradient descent
      
    def update_weights( self ) :           
        Y_pred = self.predict( self.X )
          
        # calculate gradients      
        dW = ( - ( 2 * ( self.X.T ).dot( self.Y - Y_pred ) ) +               
               ( 2 * self.l2_penality * self.W ) ) / self.m     
        db = - 2 * np.sum( self.Y - Y_pred ) / self.m 
          
        # update weights    
        self.W = self.W - self.learning_rate * dW    
        self.b = self.b - self.learning_rate * db        
        return self
      
    # Hypothetical function  h( x ) 
    def predict( self, X ) :    
        return X.dot( self.W ) + self.b

In [107]:
#data.iloc[:, :-1]
data.iloc[:, 9]

0          400
1         1100
2         1635
3         1141
4          848
          ... 
729317     296
729318     315
729319     673
729320     447
729321    1224
Name: trip_duration, Length: 725295, dtype: int64

In [12]:
import time
import datetime
#s ="2016-02-29 16:47:01"
def t(s):
    return time.mktime(datetime.datetime.strptime(s, "%Y-%m-%d %H:%M:%S").timetuple())
data['dropoff_datetime']=data['dropoff_datetime'].map(t)
data['pickup_datetime']=data['pickup_datetime'].map(t)

In [59]:
data = data.dropna()

In [108]:
from sklearn.model_selection import train_test_split
X = data.iloc[:, :-1].drop(columns=['id']).values
Y = data.iloc[:, 9].values

# Splitting dataset into train and test set
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size = 1 / 3, random_state = 0 )
  
# Model training    
model = RidgeRegression(iterations = 100, learning_rate = 0.0001, l2_penality = 1.0 )
model.fit( X_train, Y_train )

#model = RidgeRegScratch(alpha=0.1)
#model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)
# Prediction on test set
#Y_pred = model.predict( X_test )    
print( "Predicted values ", np.round( Y_pred[3], 2 ) )     
print( "Real values      ", Y_test[3] )    
#print( "Trained W        ", round( model.thetas[0], 2 ) )    
  

<ipython-input-89-191ea4906730>:46: RuntimeWarning: invalid value encountered in subtract
  self.W = self.W - self.learning_rate * dW


Predicted values  nan
Real values       1159


In [62]:
X_train.shape

(483530, 8)

In [76]:
model.W

array([nan, nan, nan, nan, nan, nan, nan, nan])

In [75]:
Y_pred = model.predict( X_test[3] )    
print( "Predicted values ", np.round( Y_pred, 2 ) )     
print( "Real values      ", Y_test[3] )    
print( "Trained W        ", round( model.W[0], 2 ) )    
print( "Trained b        ", round( model.b, 2 ) )

Predicted values  nan
Real values       40.75703048706055
Trained W         nan
Trained b         nan


In [69]:
coef = np.array([ 5.73086221e-07,  1.77857082e-10, -1.77881754e-10, -1.62690503e-07,
                7.76886457e-05,  9.87974989e-04,  1.18830294e-05,  9.98033982e-01])
intercept_ = 0.04651928801462191

In [70]:
print(np.dot(X_test[125], coef) + intercept_)
print( Y_test[125])

40.79173354054747
40.79178237915039


In [95]:
def ridge(X, y, l2):
    """Ridge Regression model with intercept term.
    L2 penalty and intercept term included via design matrix augmentation.
    This augmentation allows for the OLS estimator to be used for fitting.
    Params:
        X - NumPy matrix, size (N, p), of numerical predictors
        y - NumPy array, length N, of numerical response
        l2 - L2 penalty tuning parameter (positive scalar) 
    Returns:
        NumPy array, length p + 1, of fitted model coefficients
    """
    m, n = np.shape(X)
    upper_half = np.hstack((np.ones((m, 1)), X))
    lower = np.zeros((n, n))
    np.fill_diagonal(lower, np.sqrt(l2))
    lower_half = np.hstack((np.zeros((n, 1)), lower))
    X = np.vstack((upper_half, lower_half))
    y = np.append(y, np.zeros(n))
    return np.linalg.solve(np.dot(X.T, X), np.dot(X.T, y))

In [109]:
own = ridge( X_train, Y_train, 1 )
print(own)

[ 5.95795689e+01  4.17430413e-02 -9.99790037e-01  9.99790039e-01
  4.66543386e-03  7.34786748e-01 -4.89773539e-01 -3.97954993e-01
 -4.18817490e-01]


In [114]:
print(np.dot(X_test, own[1:9]) + own[0])
print( Y_test)

[1979.86962541 1336.83664473 1030.01212557 ...  658.09314402  988.95647892
 1686.84025487]
[1980 1337 1030 ...  658  989 1687]


In [111]:
own[1:9]

array([ 0.04174304, -0.99979004,  0.99979004,  0.00466543,  0.73478675,
       -0.48977354, -0.39795499, -0.41881749])